In [69]:
import numpy as np
import scipy as sci

lattice_parameter = 4 ## angstrom

fractional_coordi = np.array([[8.1521628680E-04,  8.1521628680E-04, 6.8994156747E-04],
                              [5.0704347734E-01,  5.0704347734E-01, 5.1280871748E-01],
                              [-8.3106175752E-03, 4.9419380842E-01, 4.8755412519E-01],
                              [4.9419380842E-01, -8.3106175752E-03, 4.8755412519E-01],
                              [4.9522968331E-01,  4.9522968331E-01, 9.8055502281E-01]])

mode4 = np.array([[7.26149E-5, 7.26149E-5, 0],
                  [0.00156, -0.00156, 0],
                  [-0.00235, 0.0016, -6.70339E-6],
                  [-0.0016, 0.00235, 6.70339E-6],
                  [-0.00133, 0.00133, 0]])


### Normalize the eigenmode with respect to the atomic mass (ref. Oxygen atoms)
def normalize(x):
    mode_normalized = np.copy(x)
    ### Ba = 56, Ti = 22, O = 8
    mode_normalized[0:1, :] = mode_normalized[0:1, :] / np.sqrt(56/8)
    mode_normalized[1:2, :] = mode_normalized[1:2, :] / np.sqrt(22/8)
    return mode_normalized

### We have to decrease or increase the magnitude of perturbation.
divide_number = 1/4
perturb = normalize(mode4)/divide_number

perturbed = perturb + fractional_coordi

max_disp = np.max(perturb) * lattice_parameter

print(f"The maximum magnitude of amplitude is {max_disp} angstrom")
print(*[str(row)[1:-2] for row in perturbed], sep='\n')
print("")
print("The original fractional coordinate is :")
print(*[str(row)[1:-2] for row in fractional_coordi], sep='\n')


The maximum magnitude of amplitude is 0.0376 angstrom
0.000925   0.000925   0.0006899
0.51080634 0.50328062 0.5128087
-0.01771062  0.50059381  0.4875273
0.48779381 0.00108938 0.4875809
0.48990968 0.50054968 0.9805550

The original fractional coordinate is :
0.00081522 0.00081522 0.0006899
0.50704348 0.50704348 0.5128087
-0.00831062  0.49419381  0.4875541
 0.49419381 -0.00831062  0.4875541
0.49522968 0.49522968 0.9805550


In [116]:
import numpy as np
import scipy as sci

lattice_parameter = 4 ## angstrom

fractional_coordi = np.array([[8.1521628680E-04,  8.1521628680E-04, 6.8994156747E-04],
                              [5.0704347734E-01,  5.0704347734E-01, 5.1280871748E-01],
                              [-8.3106175752E-03, 4.9419380842E-01, 4.8755412519E-01],
                              [4.9419380842E-01, -8.3106175752E-03, 4.8755412519E-01],
                              [4.9522968331E-01,  4.9522968331E-01, 9.8055502281E-01]])

mode8 = np.array([[8.94095743E-04,  8.94095741E-04,  1.65548041E-04],
                  [-1.40148822E-03, -1.40148822E-03, -1.00532826E-04],
                  [-1.04309215E-03, -1.26421139E-03, -3.59441039E-04],
                  [-1.26421140E-03, -1.04309215E-03, -3.59441039E-04],
                  [-1.17284141E-03, -1.17284140E-03, -4.01204213E-04]])


### Normalize the eigenmode with respect to the atomic mass (ref. Oxygen atoms)
def normalize(x):
    mode_normalized = np.copy(x)
    ### Ba = 56, Ti = 22, O = 8
    mode_normalized[0:1, :] = mode_normalized[0:1, :] / np.sqrt(56/8)
    mode_normalized[1:2, :] = mode_normalized[1:2, :] / np.sqrt(22/8)
    return mode_normalized

### We have to decrease or increase the magnitude of perturbation.
divide_number = 0.0358
perturb = normalize(mode8)/divide_number

perturbed = perturb + fractional_coordi

max_disp = np.max(perturb) * lattice_parameter

print(f"The maximum magnitude of amplitude is {max_disp} angstrom")
print(*[str(row)[1:-2] for row in perturbed], sep='\n')
print("")
print("The original fractional coordinate is :")
print(*[str(row)[1:-2] for row in fractional_coordi], sep='\n')


The maximum magnitude of amplitude is 0.0377582599243339 angstrom
0.01025478 0.01025478 0.0024377
0.48343652 0.48343652 0.5111153
-0.03744727  0.45888064  0.4775138
 0.45888064 -0.03744727  0.4775138
0.46246875 0.46246875 0.9693482

The original fractional coordinate is :
0.00081522 0.00081522 0.0006899
0.50704348 0.50704348 0.5128087
-0.00831062  0.49419381  0.4875541
 0.49419381 -0.00831062  0.4875541
0.49522968 0.49522968 0.9805550


In [173]:
import numpy as np
import scipy as sci

lattice_parameter = 3.95 ## angstrom

fractional_coordi = np.array([[8.1521628680E-04,  8.1521628680E-04, 6.8994156747E-04],
                              [5.0704347734E-01,  5.0704347734E-01, 5.1280871748E-01],
                              [-8.3106175752E-03, 4.9419380842E-01, 4.8755412519E-01],
                              [4.9419380842E-01, -8.3106175752E-03, 4.8755412519E-01],
                              [4.9522968331E-01,  4.9522968331E-01, 9.8055502281E-01]])

mode4_averaged = np.array([[7.26149E-5, 0, 0],
                  [0.00156, 0, 0],
                  [-0.00235, 0, 0],
                  [-0.0016, 0, 0],
                  [-0.00133, 0, 0]])

### Normalize the eigenmode with respect to the atomic mass (ref. Oxygen atoms)
def normalize(x):
    mode_normalized = np.copy(x)
    ### Ba = 56, Ti = 22, O = 8
    mode_normalized[0:1, :] = mode_normalized[0:1, :] / np.sqrt(137.3/16)
    mode_normalized[1:2, :] = mode_normalized[1:2, :] / np.sqrt(47.8/16)
    return mode_normalized

### We have to decrease or increase the magnitude of perturbation.

perturb = normalize(mode4_averaged)
perturbed = perturb + fractional_coordi
max_disp = np.max(perturb) * lattice_parameter
normalized_perturbed = perturb/np.max(np.abs(perturb))
normalized_max_disp = np.max(np.abs(normalized_perturbed)) * lattice_parameter
######
amp = 0.03 # Magnitude of the amplitude in Angstrom
######
final_perturbed = ((amp/lattice_parameter) * normalized_perturbed) + fractional_coordi
final_max_disp = np.max(np.abs((amp/lattice_parameter) * normalized_perturbed)) * lattice_parameter
# print(f"The maximum magnitude of amplitude is {max_disp} angstrom")
# print(*[str(row)[1:-2] for row in perturbed], sep='\n')
# print("")
print(f"The maximum magnitude of normalized amplitude is {final_max_disp} angstrom")
print(*[str(row)[1:-2] for row in final_perturbed], sep='\n')
print("")
print("The original fractional coordinate is :")
print(*[str(row)[1:-2] for row in fractional_coordi], sep='\n')


The maximum magnitude of normalized amplitude is 0.03 angstrom
0.00089533 0.00081522 0.0006899
0.50996041 0.50704348 0.5128087
-0.01590555  0.49419381  0.4875541
 0.48902279 -0.00831062  0.4875541
0.49093127 0.49522968 0.9805550

The original fractional coordinate is :
0.00081522 0.00081522 0.0006899
0.50704348 0.50704348 0.5128087
-0.00831062  0.49419381  0.4875541
 0.49419381 -0.00831062  0.4875541
0.49522968 0.49522968 0.9805550


In [179]:
import numpy as np
import scipy as sci

lattice_parameter = 3.95 ## angstrom

fractional_coordi = np.array([[8.1521628680E-04,  8.1521628680E-04, 6.8994156747E-04],
                              [5.0704347734E-01,  5.0704347734E-01, 5.1280871748E-01],
                              [-8.3106175752E-03, 4.9419380842E-01, 4.8755412519E-01],
                              [4.9419380842E-01, -8.3106175752E-03, 4.8755412519E-01],
                              [4.9522968331E-01,  4.9522968331E-01, 9.8055502281E-01]])

mode8_averaged = np.array([[8.94096E-4, 0, 0],
                  [-0.0014, 0, 0],
                  [-0.00104, 0, 0],
                  [-0.00126, 0, 0],
                  [-0.00117, 0, 0]])

### Normalize the eigenmode with respect to the atomic mass (ref. Oxygen atoms)
def normalize(x):
    mode_normalized = np.copy(x)
    ### Ba = 56, Ti = 22, O = 8
    mode_normalized[0:1, :] = mode_normalized[0:1, :] / np.sqrt(137.3/16)
    mode_normalized[1:2, :] = mode_normalized[1:2, :] / np.sqrt(47.8/16)
    return mode_normalized

### We have to decrease or increase the magnitude of perturbation.

perturb = normalize(mode8_averaged)
perturbed = perturb + fractional_coordi
max_disp = np.max(perturb) * lattice_parameter
normalized_perturbed = perturb/np.max(np.abs(perturb))
normalized_max_disp = np.max(np.abs(normalized_perturbed)) * lattice_parameter

###### important parameter
amp = 0.03 # Magnitude of the amplitude in Angstrom
###### important parameter

final_perturbed = ((amp/lattice_parameter) * normalized_perturbed) + fractional_coordi
final_max_disp = np.max(np.abs((amp/lattice_parameter) * normalized_perturbed)) * lattice_parameter
# print(f"The maximum magnitude of amplitude is {max_disp} angstrom")
# print(*[str(row)[1:-2] for row in perturbed], sep='\n')
# print("")
print(f"The maximum magnitude of normalized amplitude is {final_max_disp} angstrom")
print(*[str(row)[1:-2] for row in final_perturbed], sep='\n')
print("")
print("The original fractional coordinate is :")
print(*[str(row)[1:-2] for row in fractional_coordi], sep='\n')


The maximum magnitude of normalized amplitude is 0.03 angstrom
0.00265498 0.00081522 0.0006899
0.50216114 0.50704348 0.5128087
-0.01457945  0.49419381  0.4875541
 0.48659887 -0.00831062  0.4875541
0.48817724 0.49522968 0.9805550

The original fractional coordinate is :
0.00081522 0.00081522 0.0006899
0.50704348 0.50704348 0.5128087
-0.00831062  0.49419381  0.4875541
 0.49419381 -0.00831062  0.4875541
0.49522968 0.49522968 0.9805550


In [194]:
import numpy as np

### Generating the q-point for Abinit phonon calculation

q_point = np.zeros([251, 4])
q_point[:, 3:4] = 1.0

### X point
for i in range(0, 50):
    q_point[i:i+1, 1:2] = 0.5 - i * 0.01
### Gamma point
for i in range(51, 101):
    q_point[i:i+1, 1:2] = i * 0.01 - 0.5
for i in range(51, 101):
    q_point[i:i+1, 0:1] = i * 0.01 - 0.5
for i in range(51, 101):
    q_point[i:i+1, 2:3] = i * 0.01 - 0.5
### A point    
for i in range(101, 151):
    q_point[i:i+1, 2:3] = -0.5 + i * 0.01
q_point[101:151, 0:1] = 0.5
q_point[101:151, 1:2] = 0.5
### M point
q_point[151:201, 2:3] = 1.0
for i in range(151, 201):
    q_point[i:i+1, 0:1] = -1.0 + i * 0.01
for i in range(151, 201):
    q_point[i:i+1, 1:2] = -1.0 + i * 0.01
### Gammapoint
q_point[201:251, 0:1] = 1.0
q_point[201:251, 1:2] = 1.0
for i in range(201, 251):
    q_point[i:i+1, 2:3] = 3 - i * 0.01
### Z point

print(q_point)
print(str(q_point)).replace(' [', '').replace('[', '').replace(']', '')

[[0.   0.5  0.   1.  ]
 [0.   0.49 0.   1.  ]
 [0.   0.48 0.   1.  ]
 ...
 [1.   1.   0.52 1.  ]
 [1.   1.   0.51 1.  ]
 [1.   1.   0.5  1.  ]]
[[0.   0.5  0.   1.  ]
 [0.   0.49 0.   1.  ]
 [0.   0.48 0.   1.  ]
 ...
 [1.   1.   0.52 1.  ]
 [1.   1.   0.51 1.  ]
 [1.   1.   0.5  1.  ]]


AttributeError: 'NoneType' object has no attribute 'replace'

In [6]:
import numpy as np
from scipy import constants

br = constants.physical_constants["Bohr radius"][0]
amu = constants.physical_constants["atomic mass constant"][0]
volume = (4.2244860E+02)*(br**3)
mass = (137.327 + 47.867 + 15.999 * 3) * amu
density = mass/volume
vel = 6300
eps = 2000
q = 0.0025
print(f"the density is, {density} kg/m3")


the density is, 6185.625293538668 kg/m3


In [7]:
d24 = np.sqrt(eps*((vel**2)*density/(q**2) -  117*(10**(9))))

d24

8863529529.943245

In [30]:
import numpy as np

S4x_1 = np.array([0.0205632,  -0.1032919,   0.1212717,   0.7985830,   0.0196782,  -0.0022651])
S4x_2 = np.array([0.0205632,  -0.1032919,   0.1212717,   0.7985830,   -0.0196782,  0.0022651])
S4x_3 = np.array([-0.0205632,  0.1032919,   -0.1212717,   0.7985830,   -0.0196782,  -0.0022651])
S4x_4 = np.array([-0.0205632,  0.1032919,   -0.1212717,   0.7985830,   0.0196782,  0.0022651])
S4x_avg = (S4x_1 + S4x_2 + S4x_3 + S4x_4)/4

e2x_1 = np.array([-351.9, 387.5, -6.9, 59.19, -55.062, 2.185])
e2x_2 = np.array([-343.5, 379, -6.9, 57.89, 53.76, -2.183])
e2x_3 = np.array([350, -386, 6.9, 58.9, 54.8, 2.185])
e2x_4 = np.array([350, -385, 6.9, 58.9, -54.8, -2.185])
e2x_avg = (e2x_1 + e2x_2 + e2x_3 + e2x_4)/4


d24 = S4x_avg@e2x_avg * 10 ## T

print(S4x_avg)
print(e2x_avg)
print(f"{d24}pC/N")
print(S4x_1@e2x_1*10)

[0.       0.       0.       0.798583 0.       0.      ]
[ 1.150e+00 -1.125e+00  0.000e+00  5.872e+01 -3.255e-01  5.000e-04]
468.92793760000006pC/N
-19.18918581900003


In [25]:
S3x_avg = np.array([0, 0, 0, 0.842, 0, 0])
e3x_avg = np.array([0, 0, 0, 1.86934382, 0, 0])

d33 = S3x_avg@e3x_avg * 10

print(S3x_avg)
print(e3x_avg)
print(f"{d33}pC/N")

[0.    0.    0.    0.842 0.    0.   ]
[0.         0.         0.         1.86934382 0.         0.        ]
15.7398749644pC/N


In [53]:
import numpy as np
##
## Averaging out the compliance tensor and the pizeoelectric strain tensor.
##

s1 = np.array([[-0.0956171,  -0.1004809,   0.3198094,   0.0205632,  -0.1032919,  -0.0599606],
                [-0.1004809,  -0.0956172,   0.3198095,  -0.1032919,   0.0205632,  -0.0599606],
                [0.3198094,   0.3198095,  -0.0655071,   0.1212717,   0.1212717,   0.1261013],
                [0.0205632,  -0.1032919,   0.1212717,   0.7985830,   0.0196782,  -0.0022651],
                [-0.1032919,   0.0205632,   0.1212717,   0.0196782,   0.7985830,  -0.0022651],
                [-0.0599606,  -0.0599606,   0.1261013,  -0.0022651,  -0.0022651,   0.7749589]]) 
e_1 = np.array([[387.48719073,   -351.88977303,     -5.01286664],
                [-351.88977582,    387.48720198,     -5.01286210],
                [-6.90208691,     -6.90207070,      9.97249753],
                [-55.06183428,     59.19394126,     -0.32076248],
                [59.19393985,    -55.06183422,     -0.32076318],
                [2.18535511,     2.18535817,     -0.71516544]])

s2 = np.array([[-0.0956678,  -0.1004872,  0.3198695,   0.0205657,   0.1033005,   0.0599675],
                [-0.1004872,  -0.0956677,   0.3198694,  -0.1033005,  -0.0205657,   0.0599675],
                [0.3198695,   0.3198694,  -0.0656340,   0.1212781,  -0.1212781,  -0.1261158],
                [0.0205657,  -0.1033005,   0.1212781,   0.7985805, -0.0196793,   0.0022658],
                [0.1033005,  -0.0205657,  -0.1212781,  -0.0196793,   0.7985805,  -0.0022658],
                [0.0599675,   0.0599675,  -0.1261158,   0.0022658,  -0.0022658,   0.7749563]])
e_2 = np.array([[-379.05593679,   -343.49608068,     -5.00652616],
                [343.49608294,    379.05597919,     -5.00653114],
                [6.89467113,     -6.89467572,      9.96968882],
                [53.76640801,     57.89438201,     -0.32009430],
                [57.89437617,    53.76640839,      0.32009353],
                [2.18309824,     -2.18310421,     0.71440450]])

s3 = np.array([[-0.0956286,  -0.1004807,   0.3198234,  -0.0205644,  -0.1032936,   0.0599619],
                [-0.1004807,  -0.0956288,   0.3198235,   0.1032936,   0.0205644,   0.0599619],
                [0.3198234,   0.3198235,  -0.0655384,  -0.1212728,   0.1212728,  -0.1261047],
                [-0.0205644,   0.1032936,  -0.1212728,   0.7985825,  -0.0196786,  -0.0022651],
                [-0.1032936,   0.0205644,   0.1212728,  -0.0196786,   0.7985825,   0.0022651],
                [0.0599619,   0.0599619,  -0.1261047,  -0.0022651,   0.0022651,   0.7749584]])
e_3 = np.array([[ 385.82191098,    350.23150586,     -5.01174608],
                [-350.23150627,   -385.82191978,     -5.01174476],
                  [-6.90097266,      6.90097021,      9.97222193],
                  [54.80663028,     58.93802240,      0.32065543],
                  [58.93802077,     54.80662995,     -0.32065564],
                  [-2.18495444,      2.18495851,      0.71504010]])

s4 = np.array([[-0.0956339,  -0.1004753,   0.3198312,  -0.0205671,   0.1032930,  -0.0599614],
                [-0.1004753,  -0.0956340,   0.3198312,   0.1032930,  -0.0205671,  -0.0599614],
                [0.3198312,   0.3198312,  -0.0655622,  -0.1212718, -0.1212718,   0.1261061],
                [-0.0205671,   0.1032930,  -0.1212718,   0.7985833,   0.0196795,   0.0022646],
                [0.1032930,  -0.0205671,  -0.1212718,   0.0196795,   0.7985833,   0.0022646],
                [-0.0599614,  -0.0599614,   0.1261061,   0.0022646,   0.0022646,   0.7749587]])
e_4 = np.array([[-385.85734129,    350.26559250,     -5.01223487],
                [350.26559257,   -385.85733372,     -5.01223092],
                [6.90231903,      6.90231101,      9.97335112],
                [-54.81390579,     58.94560609,      0.32073908],
                [58.94560662,    -54.81390518,      0.32073968],
                [-2.18508819,     -2.18508688,     -0.71512415]])

np.set_printoptions(precision=5)
S_ave = (s1 + s2 + s3 + s4)/4
e_ave = (e_1 + e_2 + e_3 + e_4)/4
print(np.round(S_ave, decimals=5))
print(np.round(e_ave, decimals=5))
print(S_ave@e_ave * 10)

[[-0.09564 -0.10048  0.31983 -0.       0.       0.     ]
 [-0.10048 -0.09564  0.31983 -0.      -0.       0.     ]
 [ 0.31983  0.31983 -0.06556  0.      -0.      -0.     ]
 [-0.      -0.       0.       0.79858 -0.       0.     ]
 [ 0.      -0.      -0.      -0.       0.79858 -0.     ]
 [ 0.       0.      -0.       0.      -0.       0.77496]]
[[ 2.09896e+00  1.27781e+00 -5.01084e+00]
 [-2.08990e+00 -1.28402e+00 -5.01084e+00]
 [-1.52000e-03  1.63000e-03  9.97194e+00]
 [-3.25680e-01  5.87430e+01  1.30000e-04]
 [ 5.87430e+01 -3.25680e-01 -1.50000e-04]
 [-4.00000e-04  5.30000e-04 -2.10000e-04]]
[[ 8.89033e-02  7.29730e-02  4.17208e+01]
 [-1.15947e-01 -5.15848e-02  4.17208e+01]
 [ 2.91556e-02 -2.01551e-02 -3.85903e+01]
 [-2.60080e+00  4.69111e+02  1.30842e-03]
 [ 4.69111e+02 -2.60077e+00 -1.33884e-03]
 [-3.25524e-03  4.14829e-03 -2.14906e-03]]


In [54]:
469 * 0.814 * 2

763.5319999999999

In [56]:
0.803 * (-38)

-30.514000000000003

In [22]:
import numpy as np

ini_struc = np.array([[0.000209,   0.000209,  0.000137],
                    [0.506437,   0.506437,  0.512256],
                    [-0.008917,   0.493587,  0.487001],
                    [0.493587,  -0.008917,  0.487001],
                    [0.494623,   0.494623,  0.980002]])

def move_to_origin(struc):
    """
    Moving an atom to the origin, and move all the atoms with the atom moving to the origin.

    Returns:
        new_structure : nx3 array of the updated fractional coordinate
    """
    x = struc[0:1,0:1]
    y = struc[0:1,1:2]
    z = struc[0:1,2:3]
    
    new_x = struc[:,0:1] - x
    new_y = struc[:,1:2] - y
    new_z = struc[:,2:3] - z
    new_struc = np.hstack((new_x, new_y, new_z))
    return new_struc
    
print(move_to_origin(ini_struc))
print(*[str(row)[1:-2] for row in move_to_origin(ini_struc)], sep='\n')

[[ 0.        0.        0.      ]
 [ 0.506228  0.506228  0.512119]
 [-0.009126  0.493378  0.486864]
 [ 0.493378 -0.009126  0.486864]
 [ 0.494414  0.494414  0.979865]]
0. 0. 0
0.506228 0.506228 0.51211
-0.009126  0.493378  0.48686
 0.493378 -0.009126  0.48686
0.494414 0.494414 0.97986


In [11]:
ini_struc = np.array([[0.000485, 0.000485, 0.000444],
                    [0.50634, 0.50634, 0.512425],
                    [-0.0080, 0.494278, 0.487507],
                    [0.494278, -0.0080, 0.487507],
                    [0.495262, 0.495262, 0.980736]])

ini_struc[0:1, :]


array([[0.000485, 0.000485, 0.000444]])

In [24]:
3.980388/0.5291772108

7.521843191210984