In [1]:
import numpy as np

data = """
  0.6666666666669983  0.3333333333330017  0.5300048668121617   T   T   T
  0.3333333333330017  0.6666666666669983  0.4699951331878381   T   T   T
  0.3333333333330017  0.6666666666669983  0.0300048668121619   T   T   T
  0.6666666666669983  0.3333333333330017  0.9699951331878383   T   T   T
  0.0000000000000000 -0.0000000000000000  0.5000000000000000   T   T   T
  0.0000000000000000 -0.0000000000000000  0.0000000000000000   T   T   T
  0.6666666666669983  0.3333333333330017  0.6906433256166963   T   T   T
  0.3333333333330017  0.6666666666669983  0.3093566743833034   T   T   T
  0.3333333333330017  0.6666666666669983  0.1906433256166965   T   T   T
  0.6666666666669983  0.3333333333330017  0.8093566743833037   T   T   T
  0.8310291595843687  0.6620583191697391  0.3907613726429486   T   T   T
  0.8310291595843687  0.1689708404156313  0.3907613726429486   T   T   T
  0.3379416808302608  0.1689708404156313  0.3907613726429486   T   T   T
  0.1689708404156313  0.3379416808302608  0.6092386273570514   T   T   T
  0.1689708404156313  0.8310291595843687  0.6092386273570514   T   T   T
  0.6620583191697391  0.8310291595843687  0.6092386273570514   T   T   T
  0.1689708404156313  0.3379416808302608  0.8907613726429486   T   T   T
  0.1689708404156313  0.8310291595843687  0.8907613726429486   T   T   T
  0.6620583191697391  0.8310291595843687  0.8907613726429486   T   T   T
  0.8310291595843687  0.6620583191697391  0.1092386273570513   T   T   T
  0.8310291595843687  0.1689708404156313  0.1092386273570513   T   T   T
  0.3379416808302608  0.1689708404156313  0.1092386273570513   T   T   T
  0.0000000000000000 -0.0000000000000000  0.7500000000000000   T   T   T
  0.0000000000000000 -0.0000000000000000  0.2500000000000000   T   T   T
  0.3333333333330017  0.6666666666669983  0.5548802402853572   T   T   T
  0.6666666666669983  0.3333333333330017  0.4451197597146428   T   T   T
  0.6666666666669983  0.3333333333330017  0.0548802402853573   T   T   T
  0.3333333333330017  0.6666666666669983  0.9451197597146428   T   T   T
  0.0000000000000000 -0.0000000000000000  0.6524915450228858   T   T   T
  0.0000000000000000 -0.0000000000000000  0.3475084549771142   T   T   T
  0.0000000000000000 -0.0000000000000000  0.1524915450228858   T   T   T
  0.0000000000000000 -0.0000000000000000  0.8475084549771142   T   T   T
  0.8184227720519169  0.6368455441038340  0.7500000000000000   T   T   T
  0.8184227720519169  0.1815772279480830  0.7500000000000000   T   T   T
  0.3631544558961660  0.1815772279480830  0.7500000000000000   T   T   T
  0.1815772279480830  0.3631544558961660  0.2500000000000000   T   T   T
  0.1815772279480830  0.8184227720519169  0.2500000000000000   T   T   T
  0.6368455441038340  0.8184227720519169  0.2500000000000000   T   T   T
  0.8436033056243459  0.6872066112476833  0.5527870178546016   T   T   T
  0.8436033056243459  0.1563966943756539  0.5527870178546016   T   T   T
  0.3127933887523168  0.1563966943756539  0.5527870178546016   T   T   T
  0.1563966943756539  0.3127933887523168  0.4472129821453986   T   T   T
  0.1563966943756539  0.8436033056243459  0.4472129821453986   T   T   T
  0.6872066112476833  0.8436033056243459  0.4472129821453986   T   T   T
  0.1563966943756539  0.3127933887523168  0.0527870178546014   T   T   T
  0.1563966943756539  0.8436033056243459  0.0527870178546014   T   T   T
  0.6872066112476833  0.8436033056243459  0.0527870178546014   T   T   T
  0.8436033056243459  0.6872066112476833  0.9472129821453984   T   T   T
  0.8436033056243459  0.1563966943756539  0.9472129821453984   T   T   T
  0.3127933887523168  0.1563966943756539  0.9472129821453984   T   T   T
  0.4950394953704084  0.9900789907398149  0.6510373662505343   T   T   T
  0.4950394953704084  0.5049605046295917  0.6510373662505343   T   T   T
  0.0099210092601851  0.5049605046295917  0.6510373662505343   T   T   T
  0.5049605046295917  0.0099210092601851  0.3489626337494656   T   T   T
  0.5049605046295917  0.4950394953704084  0.3489626337494656   T   T   T
  0.9900789907398149  0.4950394953704084  0.3489626337494656   T   T   T
  0.5049605046295917  0.0099210092601851  0.1510373662505343   T   T   T
  0.5049605046295917  0.4950394953704084  0.1510373662505343   T   T   T
  0.9900789907398149  0.4950394953704084  0.1510373662505343   T   T   T
  0.4950394953704084  0.9900789907398149  0.8489626337494657   T   T   T
  0.4950394953704084  0.5049605046295917  0.8489626337494657   T   T   T
  0.0099210092601851  0.5049605046295917  0.8489626337494657   T   T   T
  0.3333333333330017  0.6666666666669983  0.7500000000000000   T   T   T
  0.6666666666669983  0.3333333333330017  0.2500000000000000   T   T   T
"""

# Split the data into lines
lines = data.split('\n')

# Remove the letter 'T' from each line and create a NumPy array
new_data_ini = np.array([list(map(float, line.split()[:-3])) for line in lines if line])

print(new_data_ini)


[[ 0.66666667  0.33333333  0.53000487]
 [ 0.33333333  0.66666667  0.46999513]
 [ 0.33333333  0.66666667  0.03000487]
 [ 0.66666667  0.33333333  0.96999513]
 [ 0.         -0.          0.5       ]
 [ 0.         -0.          0.        ]
 [ 0.66666667  0.33333333  0.69064333]
 [ 0.33333333  0.66666667  0.30935667]
 [ 0.33333333  0.66666667  0.19064333]
 [ 0.66666667  0.33333333  0.80935667]
 [ 0.83102916  0.66205832  0.39076137]
 [ 0.83102916  0.16897084  0.39076137]
 [ 0.33794168  0.16897084  0.39076137]
 [ 0.16897084  0.33794168  0.60923863]
 [ 0.16897084  0.83102916  0.60923863]
 [ 0.66205832  0.83102916  0.60923863]
 [ 0.16897084  0.33794168  0.89076137]
 [ 0.16897084  0.83102916  0.89076137]
 [ 0.66205832  0.83102916  0.89076137]
 [ 0.83102916  0.66205832  0.10923863]
 [ 0.83102916  0.16897084  0.10923863]
 [ 0.33794168  0.16897084  0.10923863]
 [ 0.         -0.          0.75      ]
 [ 0.         -0.          0.25      ]
 [ 0.33333333  0.66666667  0.55488024]
 [ 0.66666667  0.33333333

In [8]:
import numpy as np

data = """
  0.6666666666669983  0.3333333333330017  0.5243895489332889   T   T   T
  0.3333333333330017  0.6666666666669983  0.4759941629102258   T   T   T
  0.3333333333330017  0.6666666666669983  0.0243895489332888   T   T   T
  0.6666666666669983  0.3333333333330017  0.9759941629102256   T   T   T
  0.0000000000000000 -0.0000000000000000  0.5002318625827520   T   T   T
  0.0000000000000000 -0.0000000000000000  0.0002318625827519   T   T   T
  0.6666666666669983  0.3333333333330017  0.6915602957499074   T   T   T
  0.3333333333330017  0.6666666666669983  0.3084641413379181   T   T   T
  0.3333333333330017  0.6666666666669983  0.1915602957499082   T   T   T
  0.6666666666669983  0.3333333333330017  0.8084641413379181   T   T   T
  0.8303954396219970  0.6607908792449884  0.3920493000243756   T   T   T
  0.8303954396219970  0.1696045603780031  0.3920493000243756   T   T   T
  0.3392091207550115  0.1696045603780031  0.3920493000243756   T   T   T
  0.1680681081452711  0.3361362162895474  0.6085383365924528   T   T   T
  0.1680681081452711  0.8319318918547290  0.6085383365924528   T   T   T
  0.6638637837104526  0.8319318918547290  0.6085383365924528   T   T   T
  0.1696045603780031  0.3392091207550115  0.8920493000243759   T   T   T
  0.1696045603780031  0.8303954396219970  0.8920493000243759   T   T   T
  0.6607908792449884  0.8303954396219970  0.8920493000243759   T   T   T
  0.8319318918547290  0.6638637837104526  0.1085383365924529   T   T   T
  0.8319318918547290  0.1680681081452711  0.1085383365924529   T   T   T
  0.3361362162895474  0.1680681081452711  0.1085383365924529   T   T   T
  0.0000000000000000 -0.0000000000000000  0.7624808166600354   T   T   T
  0.0000000000000000 -0.0000000000000000  0.2624808166600354   T   T   T
  0.3333333333330017  0.6666666666669983  0.5557170270685005   T   T   T
  0.6666666666669983  0.3333333333330017  0.4442792587334067   T   T   T
  0.6666666666669983  0.3333333333330017  0.0557170270685006   T   T   T
  0.3333333333330017  0.6666666666669983  0.9442792587334067   T   T   T
  0.0000000000000000 -0.0000000000000000  0.6500768088930946   T   T   T
  0.0000000000000000 -0.0000000000000000  0.3484004768216711   T   T   T
  0.0000000000000000 -0.0000000000000000  0.1500768088930949   T   T   T
  0.0000000000000000 -0.0000000000000000  0.8484004768216709   T   T   T
  0.8177972288517064  0.6355944577034055  0.7504040347335675   T   T   T
  0.8177972288517064  0.1822027711482936  0.7504040347335675   T   T   T
  0.3644055422965943  0.1822027711482936  0.7504040347335675   T   T   T
  0.1822027711482936  0.3644055422965943  0.2504040347335680   T   T   T
  0.1822027711482936  0.8177972288517064  0.2504040347335680   T   T   T
  0.6355944577034055  0.8177972288517064  0.2504040347335680   T   T   T
  0.8426119772407537  0.6852239544815079  0.5520506820813371   T   T   T
  0.8426119772407537  0.1573880227592461  0.5520506820813371   T   T   T
  0.3147760455184921  0.1573880227592461  0.5520506820813371   T   T   T
  0.1570241463790797  0.3140482927581593  0.4475096582125257   T   T   T
  0.1570241463790797  0.8429758536209203  0.4475096582125257   T   T   T
  0.6859517072418406  0.8429758536209203  0.4475096582125257   T   T   T
  0.1573880227592461  0.3147760455184921  0.0520506820813372   T   T   T
  0.1573880227592461  0.8426119772407537  0.0520506820813372   T   T   T
  0.6852239544815079  0.8426119772407537  0.0520506820813372   T   T   T
  0.8429758536209203  0.6859517072418406  0.9475096582125258   T   T   T
  0.8429758536209203  0.1570241463790797  0.9475096582125258   T   T   T
  0.3140482927581593  0.1570241463790797  0.9475096582125258   T   T   T
  0.4964448424839084  0.9928896849678097  0.6516905261873257   T   T   T
  0.4964448424839084  0.5035551575160916  0.6516905261873257   T   T   T
  0.0071103150321905  0.5035551575160916  0.6516905261873257   T   T   T
  0.5031177371414471  0.0062354742829015  0.3489299100785765   T   T   T
  0.5031177371414471  0.4968822628585529  0.3489299100785765   T   T   T
  0.9937645257170986  0.4968822628585529  0.3489299100785765   T   T   T
  0.5035551575160916  0.0071103150321905  0.1516905261873255   T   T   T
  0.5035551575160916  0.4964448424839084  0.1516905261873255   T   T   T
  0.9928896849678097  0.4964448424839084  0.1516905261873255   T   T   T
  0.4968822628585529  0.9937645257170986  0.8489299100785767   T   T   T
  0.4968822628585529  0.5031177371414471  0.8489299100785767   T   T   T
  0.0062354742829015  0.5031177371414471  0.8489299100785767   T   T   T
  0.3333333333330017  0.6666666666669983  0.7448882565787118   T   T   T
  0.6666666666669983  0.3333333333330017  0.2448882565787118   T   T   T
"""

# Split the data into lines
lines = data.split('\n')

# Remove the letter 'T' from each line and create a NumPy array
new_data_fin = np.array([list(map(float, line.split()[:-3])) for line in lines if line])

print(new_data_fin)


[[ 6.66666667e-01  3.33333333e-01  5.24389549e-01]
 [ 3.33333333e-01  6.66666667e-01  4.75994163e-01]
 [ 3.33333333e-01  6.66666667e-01  2.43895489e-02]
 [ 6.66666667e-01  3.33333333e-01  9.75994163e-01]
 [ 0.00000000e+00 -0.00000000e+00  5.00231863e-01]
 [ 0.00000000e+00 -0.00000000e+00  2.31862583e-04]
 [ 6.66666667e-01  3.33333333e-01  6.91560296e-01]
 [ 3.33333333e-01  6.66666667e-01  3.08464141e-01]
 [ 3.33333333e-01  6.66666667e-01  1.91560296e-01]
 [ 6.66666667e-01  3.33333333e-01  8.08464141e-01]
 [ 8.30395440e-01  6.60790879e-01  3.92049300e-01]
 [ 8.30395440e-01  1.69604560e-01  3.92049300e-01]
 [ 3.39209121e-01  1.69604560e-01  3.92049300e-01]
 [ 1.68068108e-01  3.36136216e-01  6.08538337e-01]
 [ 1.68068108e-01  8.31931892e-01  6.08538337e-01]
 [ 6.63863784e-01  8.31931892e-01  6.08538337e-01]
 [ 1.69604560e-01  3.39209121e-01  8.92049300e-01]
 [ 1.69604560e-01  8.30395440e-01  8.92049300e-01]
 [ 6.60790879e-01  8.30395440e-01  8.92049300e-01]
 [ 8.31931892e-01  6.63863784e-

In [11]:
import numpy as np

def linear_interpolate(initial_data, final_data, steps):
    initial_array = np.array(initial_data)
    final_array = np.array(final_data)

    # Check if the shapes of the arrays match
    if initial_array.shape != final_array.shape:
        raise ValueError("Initial and final data shapes must be the same.")

    # Linearly interpolate between initial and final data
    interpolated_data = []
    for step in range(steps + 1):
        alpha = step / steps
        interpolated_point = (1 - alpha) * initial_array + alpha * final_array
        interpolated_data.append(interpolated_point)

    return np.array(interpolated_data)

# Example data
initial_data = new_data_ini

final_data = new_data_fin

# Number of interpolation steps
num_steps = 6

# Perform linear interpolation
interpolated_data = linear_interpolate(initial_data, final_data, num_steps)

# Display the result
for step, data_point in enumerate(interpolated_data):
    print(f"Step {step}: {data_point}")

Step 0: [[ 0.66666667  0.33333333  0.53000487]
 [ 0.33333333  0.66666667  0.46999513]
 [ 0.33333333  0.66666667  0.03000487]
 [ 0.66666667  0.33333333  0.96999513]
 [ 0.         -0.          0.5       ]
 [ 0.         -0.          0.        ]
 [ 0.66666667  0.33333333  0.69064333]
 [ 0.33333333  0.66666667  0.30935667]
 [ 0.33333333  0.66666667  0.19064333]
 [ 0.66666667  0.33333333  0.80935667]
 [ 0.83102916  0.66205832  0.39076137]
 [ 0.83102916  0.16897084  0.39076137]
 [ 0.33794168  0.16897084  0.39076137]
 [ 0.16897084  0.33794168  0.60923863]
 [ 0.16897084  0.83102916  0.60923863]
 [ 0.66205832  0.83102916  0.60923863]
 [ 0.16897084  0.33794168  0.89076137]
 [ 0.16897084  0.83102916  0.89076137]
 [ 0.66205832  0.83102916  0.89076137]
 [ 0.83102916  0.66205832  0.10923863]
 [ 0.83102916  0.16897084  0.10923863]
 [ 0.33794168  0.16897084  0.10923863]
 [ 0.         -0.          0.75      ]
 [ 0.         -0.          0.25      ]
 [ 0.33333333  0.66666667  0.55488024]
 [ 0.66666667  0.

In [26]:
import numpy as np

def linear_interpolate(initial_data, final_data, steps):
    initial_array = np.array(initial_data)
    final_array = np.array(final_data)

    # Check if the shapes of the arrays match
    if initial_array.shape != final_array.shape:
        raise ValueError("Initial and final data shapes must be the same.")

    # Linearly interpolate between initial and final data
    interpolated_data = []
    for step in range(steps + 1):
        alpha = step / steps
        interpolated_point = (1 - alpha) * initial_array + alpha * final_array
        interpolated_data.append(interpolated_point)

    return np.array(interpolated_data)

# Example data
initial_data = new_data_ini

final_data = new_data_fin

# Number of interpolation steps
num_steps = 7

# Perform linear interpolation
interpolated_data = linear_interpolate(initial_data, final_data, num_steps)

# Display the result
for step, data_point in enumerate(interpolated_data):
    print("Image:", step)
    formatted_data = str(data_point).replace('[', '').replace(']', '')
    print(formatted_data)


Image: 0
 0.66666667  0.33333333  0.53000487
  0.33333333  0.66666667  0.46999513
  0.33333333  0.66666667  0.03000487
  0.66666667  0.33333333  0.96999513
  0.         -0.          0.5       
  0.         -0.          0.        
  0.66666667  0.33333333  0.69064333
  0.33333333  0.66666667  0.30935667
  0.33333333  0.66666667  0.19064333
  0.66666667  0.33333333  0.80935667
  0.83102916  0.66205832  0.39076137
  0.83102916  0.16897084  0.39076137
  0.33794168  0.16897084  0.39076137
  0.16897084  0.33794168  0.60923863
  0.16897084  0.83102916  0.60923863
  0.66205832  0.83102916  0.60923863
  0.16897084  0.33794168  0.89076137
  0.16897084  0.83102916  0.89076137
  0.66205832  0.83102916  0.89076137
  0.83102916  0.66205832  0.10923863
  0.83102916  0.16897084  0.10923863
  0.33794168  0.16897084  0.10923863
  0.         -0.          0.75      
  0.         -0.          0.25      
  0.33333333  0.66666667  0.55488024
  0.66666667  0.33333333  0.44511976
  0.66666667  0.33333333  0.05